//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int id { get; set; }
        public Nullable<int> Codusuario { get; set; }
        public Nullable<int> Codoperacion { get; set; }
        public string TablaAfectada_bitacora { get; set; }
        public Nullable<System.DateTime> FechaHora_bitacora { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
