//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaDetalle
    {
        public int id { get; set; }
        public Nullable<int> Codcitae { get; set; }
        public Nullable<int> Codservicio { get; set; }
        public Nullable<int> Codmembresia { get; set; }
        public Nullable<double> Descuento_citad { get; set; }
        public Nullable<double> Subtotal_citad { get; set; }
        public string Especificaciones_citad { get; set; }
    
        public virtual CitaEncabezado CitaEncabezado { get; set; }
        public virtual Membresia Membresia { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
