//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaCliente
    {
        public int id { get; set; }
        public Nullable<int> Codcitae { get; set; }
        public Nullable<int> Codcliente { get; set; }
    
        public virtual CitaEncabezado CitaEncabezado { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
