//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.CitaClientes = new HashSet<CitaCliente>();
            this.MembresiaClientes = new HashSet<MembresiaCliente>();
        }
    
        public int id { get; set; }
        public string Nombre_cliente { get; set; }
        public Nullable<int> Codraza { get; set; }
        public Nullable<int> Codpropietario { get; set; }
        public Nullable<byte> estatus { get; set; }
        public string ImgPath_cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaCliente> CitaClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembresiaCliente> MembresiaClientes { get; set; }
        public virtual Propietario Propietario { get; set; }
        public virtual Raza Raza { get; set; }

        public HttpPostedFileBase File { get; set; }
    }
}
