//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionPerfil
    {
        public int id { get; set; }
        public Nullable<int> Codperfil { get; set; }
        public Nullable<int> Codfuncion { get; set; }
    
        public virtual Funcion Funcion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
