//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propietario()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int id { get; set; }
        public string Nombre_propietario { get; set; }
        public string Apellido_propietario { get; set; }
        public string Correo_propietario { get; set; }
        public string Descripcion_direccion { get; set; }
        public Nullable<int> Zona_direccion { get; set; }
        public string Numero_telefono { get; set; }
        public Nullable<byte> estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
