//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaWoofWoof.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_WoofWoofEntities2 : DbContext
    {
        public BD_WoofWoofEntities2()
            : base("name=BD_WoofWoofEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<CitaCliente> CitaClientes { get; set; }
        public virtual DbSet<CitaDetalle> CitaDetalles { get; set; }
        public virtual DbSet<CitaEncabezado> CitaEncabezadoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ControlMembresia> ControlMembresias { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Funcion> Funcions { get; set; }
        public virtual DbSet<FuncionPerfil> FuncionPerfils { get; set; }
        public virtual DbSet<Membresia> Membresias { get; set; }
        public virtual DbSet<MembresiaCliente> MembresiaClientes { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Propietario> Propietarios { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<Raza> Razas { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Tarifa> Tarifas { get; set; }
        public virtual DbSet<TipoPago> TipoPagoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
